version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./app-agenda/src/dados/db.json
    ports:
      - "3000:3000"
    command: json-server --watch db.json --port 3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
