version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    image: node:18-alpine
    working_dir: /app
    volumes:
      - agenda_db_data:/app
    ports:
      - "3000:3000"
    command: json-server --watch db.json --port 3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  agenda_db_data: